@startuml
class Region <<Entity>> {
    id_Key: String
    name: String
    regionType: RegionType
    claimedBy: List<Faction>
    claimbuilds: List<ClaimBuilds> |By Claimbuild|
    neighboringRegions: List<Region>
}

enum RegionType {
    SEA
    SHORE
    LAND
    MOUNTAIN
}

class ClaimBuild <<Entity>> {
    name_Key: String
    region: Region
    type: ClaimBuildType
    ownedBy: Faction
    coordinates: Coordinate
    stationedArmies: List<Army>
    createdArmies: List<Army>
    createdTradingCompanies: List<Army>
    productionSites: List<ProductionClaimbuild>
    specialBuildings: List<SpecialBuilding>
    numberOfHouses: String
    traders: String
    builtBy: List<Player>
}

enum ClaimBuildType {
    HAMLET
    VILLAGE
    TOWN
    CAPITAL
    KEEP
    CASTLE
    STRONGHOLD
}

class Faction <<Entity>> {
    name_Key: String
    factionLeader: Player
    armies: List<Army> |By Army|
    players:  List<Player> |By Player|
    regions: List<Region> |By Region|
    claimbuilds: List<ClaimBuilds> |By Claimbuild|
    allies: List<Faction>
    colorcode: String
    homeRegion: Region
    factionBuffDescr: String
}

class Player <<Entity>> {
    ign: String
    uuid: String
    discordID: String
    faction: Faction
    rpChar: RPChar
}

class RPChar <<Embeddable>> {
    name: String
    title: String
    gear: String
    pvp: Boolean
    currentRegion: Region
    boundTo: Army
}

class Coordinate <<Value Object>> {
    x: Integer
    y: Integer
    z: Integer
}

class ProductionSite <<Entity>> {
    id_Key: Long
    type: ProductionSiteType
    producedResource: String
    amountProduced: Integer
}

class ProductionClaimbuild <<Entity>> {
    claimbuild: ClaimBuild
    productionSite: ProductionSite
    count: integer
}

enum ProductionSiteType {
    FARM
    FISHING_LODGE
    MINE
    QUARRY
    MAN_FLESH_PIT
    SLAUGHTERHOUSE
    HUNTING_LODGE
    ORCHARD
    LUMBER_CAMP
    WORKSHOP
    INCOME
    PEARL_FISHER
}

enum SpecialBuilding {
    WATCHTOWER
    HOUSE_OF_HEALING
    EMBASSY
    HARBOUR
    STABLES
    BANK
    INN
    MARKET
    SHOP
    WALL
}

class Army <<Entity>> {
    name_Key: String
    armyType: ArmyType
    faction: Faction
    currentRegion: Region
    boundTo: Player
    units: List<Unit>
    sieges: List<String>
    stationedAt: ClaimBuild
    freeTokens: Integer
    originalClaimbuild: ClaimBuild
}

enum ArmyType {
    ARMY
    TRADING_COMPANY
    ARMED_TRADERS
}

class Unit <<Value Object>> {
    unitType: UnitType
    count: Integer
}

class UnitType <<Entity>> {
    unitName: String
    tokenCost: Double
}

Region -  ClaimBuild
Region - Region
Region -down- RPChar
RegionType -up- Region

Faction -down- Region
Faction -right Player
Faction -left Army
Faction -up- ClaimBuild
Faction - Faction

ClaimBuild - Player
ClaimBuild -right- ClaimBuildType
ClaimBuild -up- Coordinate
ClaimBuild - Army

ProductionSite - ProductionClaimbuild
ProductionClaimbuild - ClaimBuild
SpecialBuilding - ClaimBuild

ProductionSite -left- ProductionSiteType


RPChar - Player

Army -down- Unit
Army - Region
Army - RPChar

ArmyType - Army

UnitType - Unit

@enduml