@startuml

class War <<Entity>> {
    id_Key: Long
    name: String
    aggressors: List<WarParticipants>
    defenders: List<WarParticipants>
    startDate: LocalDateTime
    battles: List<Battle>
}

class WarParticipant <<Entity>> {
    id_Key: Long
    war_key: Long
    warParticipant: Faction
    initialParty: Boolean
    joiningDate: LocalDateTime
}

class Battle <<Entity>> {
    id_Key: Long
    declaredDate: LocalDateTime
    timeFrozenFrom: LocalDateTime
    timeFrozenUntil: LocalDateTime
    agreedBattleDate: LocalDateTime
    attackers: List<BattleParticipant>
    defenders: List<BattleParticipant>
    battleLocation: BattleLocation
}

class BattleParticipant <<Entity>> {
    id_Key: Long
    battle_Key: Long
    army: Army
    boundTo: Player
}

class BattleLocation <<Value Object>> {
    region: Region
    fieldBattle: Boolean
    claimbuild: ClaimBuild
}

class Region <<Entity>> {
    id_Key: String
    name: String
    regionType: RegionType
    claimedBy: List<Faction>
    claimbuilds: List<ClaimBuilds> |By Claimbuild|
    neighboringRegions: List<Region>
}

enum RegionType {
    SEA
    SHORE
    LAND
    MOUNTAIN
}

class ClaimBuild <<Entity>> {
    id_Key: Long
    name: String
    region: Region
    type: ClaimBuildType
    ownedBy: Faction
    coordinates: Coordinate
    stationedArmies: List<Army>
    createdArmies: List<Army>
    createdTradingCompanies: List<Army>
    productionSites: List<ProductionClaimbuild>
    specialBuildings: List<SpecialBuilding>
    numberOfHouses: String
    traders: String
    siege: String
    builtBy: List<Player>
}

enum ClaimBuildType {
    HAMLET
    VILLAGE
    TOWN
    CAPITAL
    KEEP
    CASTLE
    STRONGHOLD
}

enum InitialFaction {
    ANGMAR
    BLUE_MOUNTAINS
    BREE
    DALE
    DOL_AMROTH
    DOL_GULDUR
    DORWINION
    DUNLAND
    DURINS_FOLK
    RHUDEL
    LOTHLORIEN
    GONDOR
    GULF_OF_HARAD
    GUNDABAD
    HALF_TROLL
    LINDON
    HOBBIT
    MORDOR
    MORWAITH
    HARNENNOR
    DUNEDAIN
    RIVENDELL
    ROHAN
    NOMADS
    TAURETHRIM
    UMBAR
    ISENGARD
    WANDERER
    WOOD_ELVES
    REBELLION
    CUSTOM
}

class Faction <<Entity>> {
    id_Key: Long
    name: String
    initialFaction: InitialFaction
    factionLeader: Player
    armies: List<Army> |By Army|
    players:  List<Player> |By Player|
    regions: List<Region> |By Region|
    claimbuilds: List<ClaimBuilds> |By Claimbuild|
    allies: List<Faction>
    colorcode: String
    factionRoleId: Long
    homeRegion: Region
    factionBuffDescr: String
    aliases: List<String>

}

class Player <<Entity>> {
    id_Key: Long
    ign: String
    uuid: String
    discordID: String
    faction: Faction
    rpChar: RPChar
}

class RPChar <<Embeddable>> {
    name: String
    title: String
    gear: String
    pvp: Boolean
    currentRegion: Region
    boundTo: Army
}

class Coordinate <<Value Object>> {
    x: Integer
    y: Integer
    z: Integer
}

class ProductionSite <<Entity>> {
    id_Key: Long
    type: ProductionSiteType
    producedResource: Resource
    amountProduced: Integer
}

class Resource <<Entity>> {
    id_Key: Long
    minecraftItemId: String
    name: String
    resourceType: ResourceType
}

enum ResourceType {
    ORES
    GEMS
    STONE
    WOOD
    MINERALS
    SIEGES
    COIN
    OTHER
}

class ProductionClaimbuild <<Entity>> {
    claimbuild: ClaimBuild
    productionSite: ProductionSite
    count: integer
}

enum ProductionSiteType {
    FARM
    FISHING_LODGE
    MINE
    QUARRY
    MAN_FLESH_PIT
    SLAUGHTERHOUSE
    HUNTING_LODGE
    ORCHARD
    LUMBER_CAMP
    WORKSHOP
    INCOME
    PEARL_FISHER
}

enum SpecialBuilding {
    WATCHTOWER
    HOUSE_OF_HEALING
    EMBASSY
    HARBOUR
    STABLES
    BANK
    INN
    MARKET
    SHOP
    WALL
}

class Army <<Entity>> {
    id_Key: Long
    name: String
    armyType: ArmyType
    faction: Faction
    currentRegion: Region
    boundTo: Player
    units: List<Unit>
    sieges: List<String>
    stationedAt: ClaimBuild
    freeTokens: Integer
    originalClaimbuild: ClaimBuild
}

enum ArmyType {
    ARMY
    TRADING_COMPANY
    ARMED_TRADERS
}

class Unit <<Value Object>> {
    unitType: UnitType
    count: Integer
}

class UnitType <<Entity>> {
    unitName: String
    tokenCost: Double
}

Region -  ClaimBuild
Region - Region
Region -down- RPChar
RegionType -up- Region

Faction -down- Region
Faction -right Player
Faction -left Army
Faction -up- ClaimBuild
Faction - Faction
Faction -right- WarParticipant
Faction -right- InitialFaction

WarParticipant -up- War
War -right- Battle
Battle -up- BattleLocation
Battle -down- BattleParticipant
BattleParticipant -left- Player
BattleParticipant -left- Army



ClaimBuild - Player
ClaimBuild -right- ClaimBuildType
ClaimBuild -up- Coordinate
ClaimBuild - Army
ClaimBuild -up- BattleLocation

ProductionSite - ProductionClaimbuild
ProductionSite -down- Resource
Resource -left- ResourceType
ProductionClaimbuild - ClaimBuild
SpecialBuilding - ClaimBuild

ProductionSite -left- ProductionSiteType


RPChar - Player

Army -down- Unit
Army - Region
Army - RPChar

ArmyType - Army

UnitType - Unit

@enduml