CREATE TABLE roleplay_apps_accepted_by
(
    roleplay_application_id BIGINT NOT NULL,
    accepted_by_id          BIGINT NOT NULL,
    CONSTRAINT roleplay_apps_accepted_by_pkey PRIMARY KEY (roleplay_application_id, accepted_by_id)
);

CREATE TABLE factions
(
    name               VARCHAR(255)                            NOT NULL,
    colorcode          VARCHAR(255),
    faction_buff_descr VARCHAR(512),
    food_stockpile     INTEGER,
    home_region_id     VARCHAR(255),
    leader_id          BIGINT,
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id            BIGINT,
    initial_faction    SMALLINT,
    CONSTRAINT factions_pkey PRIMARY KEY (id)
);

CREATE TABLE players
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    discord_id VARCHAR(255)                            NOT NULL,
    ign        VARCHAR(255)                            NOT NULL,
    uuid       VARCHAR(255)                            NOT NULL,
    faction    BIGINT,
    is_staff   BOOLEAN,
    CONSTRAINT players_pkey PRIMARY KEY (id)
);

CREATE TABLE claimbuild_apps_accepted_by
(
    claimbuild_application_id BIGINT NOT NULL,
    accepted_by_id            BIGINT NOT NULL,
    CONSTRAINT claimbuild_apps_accepted_by_pkey PRIMARY KEY (claimbuild_application_id, accepted_by_id)
);

CREATE TABLE resources
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    minecraft_item_id VARCHAR(255),
    resource_name     VARCHAR(255),
    resource_type     VARCHAR(255),
    CONSTRAINT resources_pkey PRIMARY KEY (id)
);

CREATE TABLE rpchars
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version        INTEGER,
    active         BOOLEAN,
    gear           VARCHAR(255),
    heal_ends      TIMESTAMP WITHOUT TIME ZONE,
    injured        BOOLEAN,
    is_healing     BOOLEAN,
    link_to_lore   VARCHAR(255),
    name           VARCHAR(255),
    pvp            BOOLEAN,
    started_heal   TIMESTAMP WITHOUT TIME ZONE,
    title          VARCHAR(25),
    bound_to       BIGINT,
    current_region VARCHAR(255)                            NOT NULL,
    owner_id       BIGINT,
    CONSTRAINT rpchars_pkey PRIMARY KEY (id)
);

ALTER TABLE roleplay_apps_accepted_by
    ADD CONSTRAINT uk_27e1hgu7k3qyebo1d1wtfwjkn UNIQUE (accepted_by_id);

ALTER TABLE factions
    ADD CONSTRAINT uk_47tn5065hoyr2hbbodcfo5rpe UNIQUE (role_id);

ALTER TABLE players
    ADD CONSTRAINT uk_59owtm6p9ubo516h8sqiefm18 UNIQUE (uuid);

ALTER TABLE players
    ADD CONSTRAINT uk_n8wow9trjj08swysdxpd71a2l UNIQUE (discord_id);

ALTER TABLE players
    ADD CONSTRAINT uk_qtxh40udrkc84tcpyk1iqpaee UNIQUE (ign);

ALTER TABLE claimbuild_apps_accepted_by
    ADD CONSTRAINT uk_5k0wchqlaw8d2epkwir9oq9mv UNIQUE (accepted_by_id);

ALTER TABLE resources
    ADD CONSTRAINT uk_7vh3yrsm7oyl3lljngbasr6qj UNIQUE (resource_name);

ALTER TABLE rpchars
    ADD CONSTRAINT uk_c5945ixwr1xfvnhgl4xmi0cpu UNIQUE (name);

CREATE TABLE application_user
(
    id                  VARCHAR(255) NOT NULL,
    hashed_password     VARCHAR(255),
    name                VARCHAR(255),
    profile_picture_url OID,
    username            VARCHAR(255),
    CONSTRAINT application_user_pkey PRIMARY KEY (id)
);

CREATE TABLE armies
(
    name               VARCHAR(255) NOT NULL,
    army_type          VARCHAR(255) NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    free_tokens        FLOAT8       NOT NULL,
    heal_end           TIMESTAMP WITHOUT TIME ZONE,
    heal_start         TIMESTAMP WITHOUT TIME ZONE,
    hours_healed       INTEGER,
    hours_left_healing INTEGER,
    is_healing         BOOLEAN,
    is_paid            BOOLEAN,
    current_region     VARCHAR(255) NOT NULL,
    id                 BIGINT       NOT NULL,
    origin_claimbuild  BIGINT,
    stationed_at       BIGINT,
    faction            BIGINT,
    CONSTRAINT armies_pkey PRIMARY KEY (id)
);

CREATE TABLE army_sieges
(
    sieges  VARCHAR(255),
    army_id BIGINT
);

CREATE TABLE battle_attacking_armies
(
    battle_id        BIGINT NOT NULL,
    atacking_army_id BIGINT NOT NULL,
    CONSTRAINT battle_attacking_armies_pkey PRIMARY KEY (battle_id, atacking_army_id)
);

CREATE TABLE battle_defending_armies
(
    battle_id         BIGINT NOT NULL,
    defending_army_id BIGINT NOT NULL,
    CONSTRAINT battle_defending_armies_pkey PRIMARY KEY (battle_id, defending_army_id)
);

CREATE TABLE battles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agreed_battle_date TIMESTAMP WITHOUT TIME ZONE,
    field_battle       BOOLEAN,
    declared_date      TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    time_frozen_from   TIMESTAMP WITHOUT TIME ZONE,
    time_frozen_until  TIMESTAMP WITHOUT TIME ZONE,
    claimbuild_id      BIGINT,
    region_id          VARCHAR(255),
    war_id             BIGINT,
    CONSTRAINT battles_pkey PRIMARY KEY (id)
);

CREATE TABLE claimbuild_application_production_sites
(
    claimbuild_id      BIGINT NOT NULL,
    count              BIGINT,
    production_site_id BIGINT
);

CREATE TABLE claimbuild_application_special_buildings
(
    claimbuild_application_id BIGINT NOT NULL,
    special_buildings         VARCHAR(255)
);

CREATE TABLE claimbuild_apps
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version                          INTEGER,
    applied_at                       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    discord_accepted_message_link    VARCHAR(255),
    discord_application_message_link VARCHAR(255)                            NOT NULL,
    last_vote_at                     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    resolved_at                      TIMESTAMP WITHOUT TIME ZONE,
    state                            VARCHAR(255)                            NOT NULL,
    vote_count                       SMALLINT                                NOT NULL,
    claim_build_type                 VARCHAR(255)                            NOT NULL,
    claimbuild_name                  VARCHAR(255),
    x                                INTEGER,
    y                                INTEGER,
    z                                INTEGER,
    number_of_houses                 VARCHAR(255),
    siege                            VARCHAR(255),
    traders                          VARCHAR(255),
    player_id                        BIGINT                                  NOT NULL,
    owned_by_id                      BIGINT                                  NOT NULL,
    region_id                        VARCHAR(255)                            NOT NULL,
    CONSTRAINT claimbuild_apps_pkey PRIMARY KEY (id)
);

CREATE TABLE claimbuild_apps_built_by
(
    claimbuild_application_id BIGINT NOT NULL,
    built_by_id               BIGINT NOT NULL,
    CONSTRAINT claimbuild_apps_built_by_pkey PRIMARY KEY (claimbuild_application_id, built_by_id)
);

CREATE TABLE claimbuild_builders
(
    player_id     BIGINT NOT NULL,
    claimbuild_id BIGINT
);

CREATE TABLE claimbuild_special_buildings
(
    special_buildings VARCHAR(255),
    claimbuild_id     BIGINT
);

CREATE TABLE claimbuilds
(
    name                             VARCHAR(255)                            NOT NULL,
    x                                INTEGER,
    y                                INTEGER,
    z                                INTEGER,
    free_armies_remaining            INTEGER                                 NOT NULL,
    free_trading_companies_remaining INTEGER                                 NOT NULL,
    number_of_houses                 VARCHAR(255),
    siege                            VARCHAR(255),
    traders                          VARCHAR(255),
    type                             VARCHAR(255)                            NOT NULL,
    region                           VARCHAR(255)                            NOT NULL,
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owned_by                         BIGINT,
    version                          INTEGER,
    CONSTRAINT claimbuilds_pkey PRIMARY KEY (id)
);

CREATE TABLE faction_aliases
(
    faction_id BIGINT NOT NULL,
    aliases    VARCHAR(255)
);

CREATE TABLE faction_allies
(
    faction      BIGINT,
    ally_faction BIGINT
);

CREATE TABLE faction_claimed_regions
(
    region  VARCHAR(255) NOT NULL,
    faction BIGINT
);

CREATE TABLE movement_path
(
    movement_id BIGINT NOT NULL,
    actual_cost INTEGER,
    base_cost   INTEGER,
    region_id   VARCHAR(255)
);

CREATE TABLE movements
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    end_time                TIMESTAMP WITHOUT TIME ZONE,
    hours_moved             INTEGER,
    hours_until_complete    INTEGER,
    hours_until_next_region INTEGER,
    is_char_movement        BOOLEAN,
    is_currently_active     BOOLEAN,
    start_time              TIMESTAMP WITHOUT TIME ZONE,
    player_id               BIGINT,
    army_name               BIGINT,
    rpchar_id               BIGINT,
    CONSTRAINT movements_pkey PRIMARY KEY (id)
);

CREATE TABLE production_claimbuild
(
    production_site_id BIGINT NOT NULL,
    count              BIGINT,
    claimbuild_id      BIGINT
);

CREATE TABLE production_sites
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount_produced   INTEGER,
    produced_resource VARCHAR(255),
    type              VARCHAR(255),
    CONSTRAINT production_sites_pkey PRIMARY KEY (id)
);

CREATE TABLE region_neighbours
(
    region    VARCHAR(255) NOT NULL,
    neighbour VARCHAR(255) NOT NULL,
    CONSTRAINT region_neighbours_pkey PRIMARY KEY (region, neighbour)
);

CREATE TABLE regions
(
    id                                               VARCHAR(255) NOT NULL,
    has_ownership_changed_since_last_claimmap_update BOOLEAN,
    name                                             VARCHAR(255),
    region_type                                      VARCHAR(255),
    CONSTRAINT regions_pkey PRIMARY KEY (id)
);

CREATE TABLE roleplay_apps
(
    id                                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version                              INTEGER,
    applied_at                           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    discord_accepted_message_link        VARCHAR(255),
    discord_application_message_link     VARCHAR(255)                            NOT NULL,
    last_vote_at                         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    resolved_at                          TIMESTAMP WITHOUT TIME ZONE,
    state                                VARCHAR(255)                            NOT NULL,
    vote_count                           SMALLINT                                NOT NULL,
    character_name                       VARCHAR(255),
    character_title                      VARCHAR(255),
    gear                                 VARCHAR(255),
    link_to_lore                         VARCHAR(255),
    pvp                                  BOOLEAN                                 NOT NULL,
    why_do_you_want_to_be_this_character VARCHAR(255),
    player_id                            BIGINT                                  NOT NULL,
    faction_id                           BIGINT                                  NOT NULL,
    CONSTRAINT roleplay_apps_pkey PRIMARY KEY (id)
);

CREATE TABLE sample_person
(
    id            VARCHAR(255) NOT NULL,
    date_of_birth date,
    email         VARCHAR(255),
    first_name    VARCHAR(255),
    important     BOOLEAN      NOT NULL,
    last_name     VARCHAR(255),
    occupation    VARCHAR(255),
    phone         VARCHAR(255),
    CONSTRAINT sample_person_pkey PRIMARY KEY (id)
);

CREATE TABLE unit_types
(
    unit_name  VARCHAR(255) NOT NULL,
    token_cost FLOAT8       NOT NULL,
    CONSTRAINT unit_types_pkey PRIMARY KEY (unit_name)
);

CREATE TABLE units
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount_alive INTEGER,
    count        INTEGER,
    is_mounted   BOOLEAN,
    unit_type    VARCHAR(255),
    army         BIGINT,
    CONSTRAINT units_pkey PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id VARCHAR(255) NOT NULL,
    roles   VARCHAR(255)
);

CREATE TABLE war_aggressors
(
    war_id                 BIGINT NOT NULL,
    initial_party          BOOLEAN,
    joining_date           TIMESTAMP WITHOUT TIME ZONE,
    participant_faction_id BIGINT
);

CREATE TABLE war_defenders
(
    war_id                 BIGINT NOT NULL,
    initial_party          BOOLEAN,
    joining_date           TIMESTAMP WITHOUT TIME ZONE,
    participant_faction_id BIGINT
);

CREATE TABLE wars
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT wars_pkey PRIMARY KEY (id)
);

ALTER TABLE factions
    ADD CONSTRAINT fk20t2dysjgym3rgogundycuihx FOREIGN KEY (leader_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE movement_path
    ADD CONSTRAINT fk7emisc3ivfq6qe9rxcql32b13 FOREIGN KEY (region_id) REFERENCES regions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE roleplay_apps
    ADD CONSTRAINT fk7u5alh0tixpk1fsnmubp6kpcc FOREIGN KEY (faction_id) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE armies
    ADD CONSTRAINT fk_armies_faction FOREIGN KEY (faction) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE armies
    ADD CONSTRAINT fk_armies_origin_claimbuild FOREIGN KEY (origin_claimbuild) REFERENCES claimbuilds (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE armies
    ADD CONSTRAINT fk_armies_stationed_at FOREIGN KEY (stationed_at) REFERENCES claimbuilds (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE army_sieges
    ADD CONSTRAINT fk_army_sieges_army_id FOREIGN KEY (army_id) REFERENCES armies (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE battle_attacking_armies
    ADD CONSTRAINT fk_battle_attackingarmies_attackingarmy FOREIGN KEY (atacking_army_id) REFERENCES armies (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE battle_attacking_armies
    ADD CONSTRAINT fk_battle_attackingarmies_battle FOREIGN KEY (battle_id) REFERENCES battles (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE battle_defending_armies
    ADD CONSTRAINT fk_battle_defendingarmies_battle FOREIGN KEY (battle_id) REFERENCES battles (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE battle_defending_armies
    ADD CONSTRAINT fk_battle_defendingarmies_defendingarmy FOREIGN KEY (defending_army_id) REFERENCES armies (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE battles
    ADD CONSTRAINT fk_battle_location_claimbuild_id FOREIGN KEY (claimbuild_id) REFERENCES claimbuilds (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE battles
    ADD CONSTRAINT fk_battle_location_region_id FOREIGN KEY (region_id) REFERENCES regions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE battles
    ADD CONSTRAINT fk_battle_war_id FOREIGN KEY (war_id) REFERENCES wars (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_application_production_sites
    ADD CONSTRAINT fk_claimbuild_application_production_sites_ FOREIGN KEY (claimbuild_id) REFERENCES claimbuild_apps (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_application_production_sites
    ADD CONSTRAINT fk_claimbuild_application_production_sites_production_site_id FOREIGN KEY (production_site_id) REFERENCES production_sites (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_apps
    ADD CONSTRAINT fk_claimbuild_apps_owned_by_id FOREIGN KEY (owned_by_id) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_apps
    ADD CONSTRAINT fk_claimbuild_apps_region_id FOREIGN KEY (region_id) REFERENCES regions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_builders
    ADD CONSTRAINT fk_claimbuild_builders_claimbuild_id FOREIGN KEY (claimbuild_id) REFERENCES claimbuilds (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuilds
    ADD CONSTRAINT fk_claimbuild_owned_by FOREIGN KEY (owned_by) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_special_buildings
    ADD CONSTRAINT fk_claimbuild_special_buildings_claimbuild_id FOREIGN KEY (claimbuild_id) REFERENCES claimbuilds (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE armies
    ADD CONSTRAINT fk_current_region FOREIGN KEY (current_region) REFERENCES regions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE faction_aliases
    ADD CONSTRAINT fk_faction_aliases_faction_id FOREIGN KEY (faction_id) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE faction_allies
    ADD CONSTRAINT fk_faction_allies_ally_faction FOREIGN KEY (ally_faction) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE faction_allies
    ADD CONSTRAINT fk_faction_allies_faction FOREIGN KEY (faction) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE faction_claimed_regions
    ADD CONSTRAINT fk_faction_claimed_regions_faction FOREIGN KEY (faction) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE movements
    ADD CONSTRAINT fk_movement_army_name FOREIGN KEY (army_name) REFERENCES armies (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE movements
    ADD CONSTRAINT fk_movement_rpchar_id FOREIGN KEY (rpchar_id) REFERENCES rpchars (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE region_neighbours
    ADD CONSTRAINT fk_neighbour FOREIGN KEY (neighbour) REFERENCES regions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE players
    ADD CONSTRAINT fk_player_faction FOREIGN KEY (faction) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_builders
    ADD CONSTRAINT fk_player_id FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE production_claimbuild
    ADD CONSTRAINT fk_production_claimbuild_claimbuild_id FOREIGN KEY (claimbuild_id) REFERENCES claimbuilds (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE production_claimbuild
    ADD CONSTRAINT fk_production_site_id FOREIGN KEY (production_site_id) REFERENCES production_sites (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE production_sites
    ADD CONSTRAINT fk_production_site_resource_name FOREIGN KEY (produced_resource) REFERENCES resources (resource_name) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE region_neighbours
    ADD CONSTRAINT fk_region FOREIGN KEY (region) REFERENCES regions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE rpchars
    ADD CONSTRAINT fk_rpchar_bound_to FOREIGN KEY (bound_to) REFERENCES armies (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE rpchars
    ADD CONSTRAINT fk_rpchar_current_region FOREIGN KEY (current_region) REFERENCES regions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE rpchars
    ADD CONSTRAINT fk_rpchars_owner FOREIGN KEY (owner_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE units
    ADD CONSTRAINT fk_unit_army FOREIGN KEY (army) REFERENCES armies (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE units
    ADD CONSTRAINT fk_unit_type FOREIGN KEY (unit_type) REFERENCES unit_types (unit_name) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE war_aggressors
    ADD CONSTRAINT fk_war_aggressors_war_id FOREIGN KEY (war_id) REFERENCES wars (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE war_defenders
    ADD CONSTRAINT fk_war_defenders_war_id FOREIGN KEY (war_id) REFERENCES wars (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE roleplay_apps
    ADD CONSTRAINT fkak8ge4g630evoyy1fv2833tt FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_apps_accepted_by
    ADD CONSTRAINT fkaoo6cq55ramihbkkl1e5p94om FOREIGN KEY (accepted_by_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE movements
    ADD CONSTRAINT fkb7476f8q5njenlna6yiixbfqt FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE factions
    ADD CONSTRAINT fke6ypaht2bxdcuddlc5xftq9te FOREIGN KEY (home_region_id) REFERENCES regions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE roleplay_apps_accepted_by
    ADD CONSTRAINT fken8yb0bxswf3hh7d0148x0skb FOREIGN KEY (accepted_by_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE roleplay_apps_accepted_by
    ADD CONSTRAINT fkh1ilsqvciqumnbvh6jd5ax31p FOREIGN KEY (roleplay_application_id) REFERENCES roleplay_apps (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_application_special_buildings
    ADD CONSTRAINT fkh49su3y1onc1xdiwdkl44c1ch FOREIGN KEY (claimbuild_application_id) REFERENCES claimbuild_apps (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE war_defenders
    ADD CONSTRAINT fkiuo9k6nivhdwwr6q2ktfoxgjb FOREIGN KEY (participant_faction_id) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_apps
    ADD CONSTRAINT fkkl3l99tghp77np2kqncamske5 FOREIGN KEY (player_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_apps_built_by
    ADD CONSTRAINT fkmi1j8cfpneyy42wgamhhw4jxf FOREIGN KEY (built_by_id) REFERENCES players (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE war_aggressors
    ADD CONSTRAINT fkn288l28fyvw8jrmpvag32qd36 FOREIGN KEY (participant_faction_id) REFERENCES factions (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE movement_path
    ADD CONSTRAINT fkp5tu7ll8bt129nbhov91dr00f FOREIGN KEY (movement_id) REFERENCES movements (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT fkq0h6vpf3crn504yyep1hdv0vc FOREIGN KEY (user_id) REFERENCES application_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_apps_built_by
    ADD CONSTRAINT fkqbl9cikil8y0icpv9p75dk70 FOREIGN KEY (claimbuild_application_id) REFERENCES claimbuild_apps (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE claimbuild_apps_accepted_by
    ADD CONSTRAINT fkr5s8sle9yqrtftu3ws93enifo FOREIGN KEY (claimbuild_application_id) REFERENCES claimbuild_apps (id) ON UPDATE NO ACTION ON DELETE NO ACTION;